name: Documentation Request
description: Create an issue for missing or incorrect documentation
title: "[Documentation]: "
labels: ["T:Docs"]
body:
  - type: markdown
    attributes:
      value: |
        ✰  Thanks for opening an issue! ✰    
        Please let us know what you would like to see added to the documentation or if you've found any errors in the existing documentation.

  - type: textarea
    id: what-happened
    attributes:
      label: Summary
      placeholder: Description of what you would like to see
    validations:
      required: true
